name: Build and deploy docker image to docker hub
on:
  push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Add PYTHON_VERSION env property, parsed from Dockerfile
        run: echo "PYTHON_VERSION=`head -n 1 < Dockerfile | perl -ne 'print $1  if /.+:(.+) as*/'`" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Build and push with commit hash tag
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER }}/python3-arm:${{ env.SHORT_SHA }}
      -
        name: Build and push with python version tag
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER }}/python3-arm:${{ env.PYTHON_VERSION }}
      -
        name: Build and push with latest tag
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER }}/python3-arm:latest
